name: Bug Report
description: Report an issue about the mod.
title: Bug Report
labels: ["bug"]

body:
  - type: dropdown
    id: platform
    attributes:
      label: Platforms
      description: The device/operating system(s) that you know the bug occurs on.
      multiple: true
      options:
        - Android
        - iOS
        - Mac
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    id: build
    attributes:
      label: Mindustry Build
      description: The build number of Mindustry. 
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version
      description: The version or commit of Allure that you are using. 
      placeholder: Please check the Github repository for the latest commit.
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Explain the bug you've encountered.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Method
      description: How you caused the bug. Include screenshots.
    validations:
      required: true
  - type: textarea
    id: save
    attributes:
      label: Save File
      description: The save file of the map you encountered the bug in.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Game Logs
      description: The last log from your game (last_log.txt). This contains crashes and errors that I will need to know.
    validations:
      required: true
  - type: checkboxes
    id: submission
    attributes:
      label: Le Checkboxe
      description: Read these simple questions, then check them once you understand.
      options:
        - label: **I have disabled all other mods and reproduced this bug anyways.**
          required: true
        - label: I have updated to the latest release/BE (Bleeding Edge) version before submitting this report.
          required: true
        - label: I have confirmed that this issue has not already been reported.
          required: true